(function(g){var window=this;var dra=function(a,b){return g.Vb(a,b)},$5=function(a,b,c){a.w.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.E)()).toString(36));
return a},b6=function(a,b,c){g.Ia(c)||(c=[String(c)]);
g.Wm(a.w,b,c)},era=function(a,b){var c=[];
g.pk(b,function(d){try{var e=g.In.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Hn(e)&&c.push(d)},a);
return c},fra=function(a,b){var c=era(a,b);
(0,g.y)(c,function(d){g.In.prototype.remove.call(this,d)},a)},gra=function(a){if(a.cd){if(a.cd.locationOverrideToken)return{locationOverrideToken:a.cd.locationOverrideToken};
if(null!=a.cd.latitudeE7&&null!=a.cd.longitudeE7)return{latitudeE7:a.cd.latitudeE7,longitudeE7:a.cd.longitudeE7}}return null},hra=function(a,b){g.Ya(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},ira=function(a,b){var c=b instanceof g.yc?b:g.Cc(b,/^data:image\//i.test(b));
a.src=g.zc(c)},d6=function(){},jra=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},kra=function(a){if(a.md&&"function"==typeof a.md)return a.md();
if("string"===typeof a)return a.split("");if(g.Ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},lra=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ja(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.Yd&&"function"==typeof a.Yd)var c=a.Yd();else if(a.md&&"function"==typeof a.md)c=void 0;else if(g.Ja(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=kra(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},mra=function(a,b,c,d){var e=new g.Km(null,void 0);
a&&g.Lm(e,a);b&&g.Mm(e,b);c&&g.Nm(e,c);d&&(e.u=d);return e},e6=function(a,b){g.Do[a]=!0;
var c=g.Bo();c&&c.publish.apply(c,arguments);g.Do[a]=!1},f6=function(a){try{var b=(0,g.Jx)(),c=(0,g.Ix)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},nra=function(){var a=(0,g.Ix)();
a&&fra(a,a.o.hf(!0))},g6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.w=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Hm;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",ora(this,a.capabilities||""),pra(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},ora=function(a,b){a.capabilities.clear();
(0,g.Vd)(b.split(","),g.Oa(dra,qra)).forEach(function(c){a.capabilities.add(c)})},pra=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},h6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},i6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},rra=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},sra=function(a){return new h6(a)},tra=function(a){return g.Ia(a)?(0,g.H)(a,sra):[]},j6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},k6=function(a){return g.Ia(a)?"["+(0,g.H)(a,j6).join(",")+"]":"null"},l6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},ura=function(a){return(0,g.H)(a,function(b){return{key:b.id,
name:b.name}})},m6=function(a,b){return g.Va(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},n6=function(a,b){return g.Va(a,function(c){return i6(c,b)})},o6=function(){var a=g.Lx("yt-remote-connected-devices")||[];
g.ob(a);return a},vra=function(a){if(g.Za(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(d,e){return 0==e?d:d.substring(c.length)})},wra=function(a){g.Kx("yt-remote-connected-devices",a,86400)},q6=function(){if(p6)return p6;
var a=g.Lx("yt-remote-device-id");a||(a=l6(),g.Kx("yt-remote-device-id",a,31536E3));for(var b=o6(),c=1,d=a;g.Ya(b,d);)c++,d=a+"#"+c;return p6=d},r6=function(){var a=o6(),b=q6();
g.Ya(a,b);g.QM()&&g.qb(a,b);a=vra(a);if(g.Za(a))try{g.Gr("remote_sid")}catch(c){}else try{g.Fr("remote_sid",a.join(","),-1)}catch(c){}},xra=function(){return g.Lx("yt-remote-session-browser-channel")},yra=function(){return g.Lx("yt-remote-local-screens")||[]},zra=function(){g.Kx("yt-remote-lounge-token-expiration",!0,86400)},Ara=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)(yra(),function(d){return d.loungeToken}),c=(0,g.H)(a,function(d){return d.loungeToken});
(0,g.si)(c,function(d){return!g.Ya(b,d)})&&zra();
g.Kx("yt-remote-local-screens",a,31536E3)},Bra=function(a,b){g.Kx("yt-remote-session-browser-channel",a);
g.Kx("yt-remote-session-screen-id",b);var c=o6(),d=q6();g.Ya(c,d)||c.push(d);wra(c);r6()},s6=function(a){a||(f6("yt-remote-session-screen-id"),f6("yt-remote-session-video-id"));
r6();a=o6();g.bb(a,q6());wra(a)},Cra=function(){if(!t6){var a=g.Sn();
a&&(t6=new g.Cn(a))}return t6?!!t6.get("yt-remote-use-staging-server"):!1},Dra=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Era=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?Fra(a.shift(),function(){u6(a)}):v6()},Gra=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Fra=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},v6=function(){var a=Era();
a&&a(!1,"No cast extension found")},Ira=function(){if(Hra){var a=2,b=Era(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Fra("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},Jra=function(){Ira();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},w6=function(a,b,c){g.A.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.Uc=b;this.B=(0,g.x)(this.iD,this);this.o=!1;this.u=0;this.w=this.Fa=null;this.A=[]},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return jra(a)},y6=function(){},z6=function(){},Kra=function(){},Mra=function(a){return(a=Lra(a))?new ActiveXObject(a):new XMLHttpRequest},Lra=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.D=d||1;this.B=45E3;this.A=new g.W_(this);this.u=new g.vf;this.u.setInterval(250)},Ora=function(a,b,c){a.fi=1;
a.Vf=a6(b.clone());a.wh=c;a.C=!0;Nra(a,null)},B6=function(a,b,c,d,e){a.fi=1;
a.Vf=a6(b.clone());a.wh=null;a.C=c;e&&(a.Jz=!1);Nra(a,d)},Nra=function(a,b){a.Ki=(0,g.E)();
C6(a);a.Dg=a.Vf.clone();b6(a.Dg,"t",a.D);a.Sk=0;a.tc=a.o.Zo(a.o.Hk()?b:null);0<a.Ip&&(a.En=new g.kl((0,g.x)(a.NA,a,a.tc),a.Ip));a.A.ha(a.tc,"readystatechange",a.tM);var c=a.ah?g.ac(a.ah):{};a.wh?(a.jo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.Dg,a.jo,a.wh,c)):(a.jo="GET",a.Jz&&!g.Kd&&(c.Connection="close"),a.tc.send(a.Dg,a.jo,null,c));a.o.oe(1)},Rra=function(a,b,c){for(var d=!0;!a.Ng&&a.Sk<c.length;){var e=Pra(a,c);
if(e==D6){4==b&&(a.lg=4,E6(15),d=!1);break}else if(e==Qra){a.lg=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.lg=1,E6(17),d=!1);a.pe=a.pe&&d;d||(G6(a),H6(a))},Pra=function(a,b){var c=a.Sk,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return Qra;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Sk=d+c;return e},Tra=function(a,b){a.Ki=(0,g.E)();
C6(a);var c=b?window.location.hostname:"";a.Dg=a.Vf.clone();$5(a.Dg,"DOMAIN",c);$5(a.Dg,"t",a.D);try{a.we=new ActiveXObject("htmlfile")}catch(n){G6(a);a.lg=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in Sra)k=I6[l]=Sra[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.rc("b/12014412"),d+"</body></html>");a.we.open();a.we.write(g.Mc(c));a.we.close();a.we.parentWindow.m=(0,g.x)(a.JL,a);a.we.parentWindow.d=(0,g.x)(a.Qy,a,!0);a.we.parentWindow.rpcClose=(0,g.x)(a.Qy,a,!1);c=a.we.createElement("DIV");a.we.parentWindow.document.body.appendChild(c);d=g.Bc(a.Dg.toString());d=g.Zc(g.zc(d));d=g.Rc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.o.oe(1)},C6=function(a){a.Qs=(0,g.E)()+a.B;
Ura(a,a.B)},Ura=function(a,b){if(null!=a.Xi)throw Error("WatchDog timer not null");
a.Xi=J6((0,g.x)(a.QL,a),b)},K6=function(a){a.Xi&&(g.v.clearTimeout(a.Xi),a.Xi=null)},H6=function(a){a.o.Fv()||a.Ng||a.o.wn(a)},G6=function(a){K6(a);
g.he(a.En);a.En=null;a.u.stop();g.Y_(a.A);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.we&&(a.we=null)},F6=function(a,b){try{a.o.Jy(a,b),a.o.oe(4)}catch(c){}},Wra=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Vra(a,b,function(k){k?c(!0):g.v.setTimeout(function(){Wra(a,b,c,d,f)},f)})}},Vra=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
ira(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Xra=function(a){this.o=a;
this.u=new y6},Yra=function(a){var b=M6(a.o,a.gj,"/mail/images/cleardot.gif");
a6(b);Wra(b.toString(),5E3,(0,g.x)(a.gC,a),3,2E3);a.oe(1)},O6=function(a){var b=a.o.H;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.xd=new A6(a,void 0,void 0,void 0),a.xd.ah=a.Gp,b=a.o,b=M6(b,b.Hk()?a.Dj:null,a.Hp),E6(5),!g.Id||g.md(10))b6(b,"TYPE","xmlhttp"),B6(a.xd,b,!1,a.Dj,!1);else{b6(b,"TYPE","html");var c=a.xd;a=!!a.Dj;c.fi=3;c.Vf=a6(b.clone());Tra(c,a)}},P6=function(a){g.Je.call(this);
this.headers=new g.Hm;this.P=a||null;this.w=!1;this.L=this.o=null;this.Z=this.H="";this.C=0;this.A="";this.B=this.da=this.G=this.U=!1;this.D=0;this.J=null;this.aa="";this.R=this.V=!1},Zra=function(a){return g.Id&&g.ld(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},$ra=function(a){return"content-type"==a.toLowerCase()},bsa=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;asa(a);Q6(a)},asa=function(a){a.U||(a.U=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},dsa=function(a){if(a.w&&"undefined"!=typeof g.d0)if(a.L[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.wf(a.Hv,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Tg(1,String(a.H));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!csa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";asa(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){esa(a);
var c=a.o,d=a.L[0]?g.Fa:null;a.o=null;a.L=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},esa=function(a){a.o&&a.R&&(a.o.ontimeout=null);
a.J&&(g.v.clearTimeout(a.J),a.J=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.Z+" "+a.H+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new y6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},fsa=function(a,b){this.o=a;
this.map=b;this.context=null},gsa=function(a){g.je.call(this,"statevent",a)},hsa=function(a,b){g.je.call(this,"timingevent",a);
this.size=b},isa=function(a){g.je.call(this,"serverreachability",a)},lsa=function(a){jsa(a);
if(3==a.o){var b=a.kk++,c=a.Wl.clone();$5(c,"SID",a.w);$5(c,"RID",b);$5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.w,b,void 0);b.fi=2;b.Vf=a6(c.clone());ira(new Image,b.Vf.toString());b.Ki=(0,g.E)();C6(b)}ksa(a)},msa=function(a){a.BC(1,0);
a.Wl=M6(a,null,a.Fp);W6(a)},jsa=function(a){a.Yf&&(a.Yf.abort(),a.Yf=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.jf&&(g.v.clearTimeout(a.jf),a.jf=null);X6(a);a.qd&&(a.qd.cancel(),a.qd=null);a.fg&&(g.v.clearTimeout(a.fg),a.fg=null)},nsa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new fsa(a.WH++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.qd||a.fg||(a.fg=J6((0,g.x)(a.Py,a),0),a.Vh=0)},psa=function(a,b){if(1==a.o){if(!b){a.kk=Math.floor(1E5*Math.random());
var c=a.kk++,d=new A6(a,"",c,void 0);d.ah=null;var e=Y6(a),f=a.Wl.clone();$5(f,"RID",c);$5(f,"CVER","1");V6(a,f);Ora(d,f,e);a.qd=d;a.o=2}}else 3==a.o&&(b?osa(a,b):0==a.u.length||a.qd||osa(a))},osa=function(a,b){if(b)if(6<a.Og){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.kk-1;var d=Y6(a)}else c=b.G,d=b.wh;else c=a.kk++,d=Y6(a);var e=a.Wl.clone();$5(e,"SID",a.w);$5(e,"RID",c);$5(e,"AID",a.si);V6(a,e);c=new A6(a,a.w,c,a.Vh+1);c.ah=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.qd=c;Ora(c,e,d)},V6=function(a,b){if(a.Rc){var c=a.Rc.Zu();
c&&g.Jb(c,function(d,e){$5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Og&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.Og?e:f-d;try{g.Jb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},qsa=function(a){a.Sb||a.jf||(a.D=1,a.jf=J6((0,g.x)(a.Oy,a),0),a.Qh=0)},Z6=function(a){if(a.Sb||a.jf||3<=a.Qh)return!1;
a.D++;a.jf=J6((0,g.x)(a.Oy,a),rsa(a,a.Qh));a.Qh++;return!0},N6=function(a,b,c){a.fo=c;
a.Ee=b.yf;a.C||msa(a)},X6=function(a){null!=a.Sg&&(g.v.clearTimeout(a.Sg),a.Sg=null)},rsa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.Rc&&(c=null);var d=(0,g.x)(a.eN,a);c||(c=new g.Km("//www.google.com/images/cleardot.gif"),a6(c));Vra(c.toString(),1E4,d)}else E6(2);ssa(a,b)},ssa=function(a,b){a.o=0;
a.Rc&&a.Rc.qu(b);ksa(a);jsa(a)},ksa=function(a){a.o=0;
a.Ee=-1;if(a.Rc)if(0==a.A.length&&0==a.u.length)a.Rc.To();else{g.eb(a.A);var b=g.eb(a.u);a.A.length=0;a.u.length=0;a.Rc.To(b)}},M6=function(a,b,c){var d=g.Sm(c);
if(""!=d.o)b&&g.Mm(d,b+"."+d.o),g.Nm(d,d.B);else{var e=window.location;d=mra(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.rj&&g.Jb(a.rj,function(f,k){$5(d,k,f)});
$5(d,"VER",a.Og);V6(a,d);return d},J6=function(a,b){if(!g.Ka(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new gsa(a7,a))},tsa=function(){},usa=function(){this.o=[];
this.u=[]},vsa=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.A.call(this);
this.o=new g.K(this.AL,0,this);g.D(this,this.o);this.Uc=5E3;this.u=0;if(g.Ka(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ka(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.J=a;
this.C=b;this.w=new g.Bn;this.u=new b7(this.EM,this);this.o=null;this.fb=!1;this.B=null;this.H="";this.G=this.A=0;this.D=[];this.R=c||!1},wsa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.fo,sessionId:a.o.w,arrayId:a.o.si}},xsa=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&psa(a.o),lsa(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},ysa=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.Tg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Ug(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Gb(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.ch(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Oa(a.A,d,!0),onError:g.Oa(a.w,e),Pd:g.Oa(a.B,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Cp(b,a)},Csa=function(){var a=zsa;
Asa();h7.push(a);Bsa(h7)},i7=function(a,b){Asa();
var c=h7,d=Dsa(a,String(b));g.Za(c)?Esa(d):(Bsa(c),(0,g.y)(c,function(e){e(d)}))},Asa=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ea("yt.mdx.remote.debug.handlers_",h7,void 0))},Esa=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},Bsa=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},Dsa=function(a,b){var c=((0,g.E)()-Fsa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.Q.call(this);
this.D=a;this.o=[]},Gsa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},Hsa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Vd)(a.o,function(f){return!!m6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Gsa(a,b[d])||c;return c},Isa=function(a,b){var c=a.o.length;
a.o=(0,g.Vd)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.Q.call(this);
this.C=a;this.B=b;this.w=c;this.A=d;this.u=0;this.o=null;this.Fa=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+k6(this.o))},Jsa=function(a){if(a.o.length){var b=(0,g.H)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.sD,a),(0,g.x)(a.rD,a))}},o7=function(a){var b=tra(yra());
b=(0,g.Vd)(b,function(c){return!c.uuid});
return Hsa(a,b)},q7=function(a,b){Ara((0,g.H)(a.o,rra));
b&&zra()},s7=function(a,b){g.Q.call(this);
this.C=b;var c=g.Lx("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ya(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.Qk(this.o))},Ksa=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(c6(b)!=c6(a.o))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.Qk(a.o)),a.o=b,a.S("screenChange"));Lsa(a)},u7=function(a){isNaN(a.w)||g.Ao(a.w);
a.w=g.yo((0,g.x)(a.Tr,a),0<a.A&&a.A<(0,g.E)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},Msa=function(a){var b={};
(0,g.y)(a.C(),function(c){c.token?b[c.token]=c.id:this.Jb("Requesting availability of screen w/o lounge token.")});
return b},Lsa=function(a){a=g.Rb(g.Kb(a.o,function(b){return b}));
g.ob(a);a.length?g.Kx("yt-remote-online-screen-ids",a.join(","),60):f6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};Nsa(this)},Psa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.Kd();if(k=(c?n6(k,c):null)||n6(k,b)){k.uuid=b;var l=w7(a,k);Ksa(a.u,l,function(m){e(m?l:null)})}else c?Osa(a,c,(0,g.x)(function(m){var n=w7(this,new h6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Ksa(this.u,n,function(q){e(q?n:null)})},a),f):e(null)},Qsa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},Osa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Cp(f7(a.C,"/pairing/get_lounge_token_batch"),e)},Rsa=function(a){a.o=a.w.Kd();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+k6(a.o))},Nsa=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.zD,a));Rsa(a);a.A=tra(g.Lx("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+k6(a.A));a.u=new s7(a.C,(0,g.x)(a.Kd,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=n6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Kx("yt-remote-automatic-screen-cache",(0,g.H)(a.A,rra)));x7(a);a.B[b.uuid]=b.id;g.Kx("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.Lx("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.Q.call(this);
this.L=c;this.H=a;this.u=b;this.w=null},z7=function(a,b){i7(a.L,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.ON,this);this.B=(0,g.x)(this.bM,this);this.A=g.yo((0,g.x)(function(){Ssa(this,null)},this),12E4)},Tsa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Qk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Fa,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.Qk(b))},Ssa=function(a,b){g.Ao(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.yn,a),d=(0,g.x)(a.Od,a);a.zv(b,c,d,5)}}else a.Od(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.P=c;this.B=null;this.D=g.Fa;this.C=NaN;this.R=(0,g.x)(this.RN,this);this.o=g.Fa},Usa=function(a){a.o=a.H.TA(a.J,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Fa;
this.yn(b)},a),(0,g.x)(function(b){this.o=g.Fa;
this.Od(b)},a))},Vsa=function(a){var b={};
b.pairingCode=a.J;b.theme=a.P;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Cra()&&(b.env_useStageMdx=1);return g.ah(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.yo((0,g.x)(this.ti,this,null),150)},D7=function(a,b,c,d){g.Q.call(this);
this.u=a;this.D=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.IK,this)},Wsa=function(a,b){return b?g.Va(a.w,function(c){return i6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},zsa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.he(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.u):a.S("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.My,a,b)),b.w?a.S("yt-remote-cast2-session-change",b.w):c&&a.o.ti(null)):a.S("yt-remote-cast2-session-change",null))},Xsa=function(a){var b=a.u.SA(),c=a.o&&a.o.u;
a=(0,g.H)(b,function(d){c&&i6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Wsa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},cta=function(a,b,c,d,e,f,k){Ysa()?Zsa(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?$sa(a,c):(window.__onGCastApiAvailable=function(l,m){l?$sa(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),f6("yt-remote-cast-available"),f6("yt-remote-cast-receiver"),ata(),c(!1))},d?g.Qo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Jra():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?v6():(Ira(),u6(bta.map(Gra))))):H7("Cannot initialize because not running Chrome")},ata=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ea("yt.mdx.remote.cloudview.instance_",null,void 0);dta(!1);g.Lo(M7);M7.length=0},N7=function(){return!!g.Lx("yt-remote-cast-installed")},eta=function(){var a=g.Lx("yt-remote-cast-receiver");
return a?a.friendlyName:null},fta=function(){H7("clearCurrentReceiver");
f6("yt-remote-cast-receiver")},gta=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.Fo("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},Ysa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Ss||a},hta=function(a,b){L7().init(a,b)},Zsa=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Kx("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.Kx("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.Kx("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+j6(f));
f||f6("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ea("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},$sa=function(a,b){K7(!0);
I7(!1);hta(a,function(c){c?(dta(!0),g.No("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),f6("yt-remote-cast-available"),f6("yt-remote-cast-receiver"),ata());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.Kx("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},dta=function(a){H7("setApiReady_ "+a);
g.Ea("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ea("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.D=0;this.o=null;this.hasNext=this.Fe=!1;this.H=this.G=this.u=this.A=0;this.w=NaN;this.B=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Fe=!1;a.hasNext=!1;a.D=0;a.C=(0,g.E)();a.A=0;a.u=0;a.G=0;a.H=0;a.w=NaN;a.B=!1},T7=function(a){return 1==a.playerState?((0,g.E)()-a.C)/1E3:0},U7=function(a,b){a.D=b;
a.C=(0,g.E)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.E)()-a.C)/1E3+a.D;
case -1E3:return 0}return a.D},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.o);b.hasPrevious=a.Fe;b.hasNext=a.hasNext;b.playerTime=a.D;b.playerTimeAt=a.C;b.seekableStart=a.A;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.w;return b},Z7=function(a,b){g.Q.call(this);
this.o=0;this.A=a;this.C=[];this.B=new usa;this.w=this.u=null;this.H=(0,g.x)(this.FI,this);this.D=(0,g.x)(this.pk,this);this.G=(0,g.x)(this.DI,this);this.J=(0,g.x)(this.SI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ts,this),ita(this))):c=3;0!=c&&(b?this.Ts(c):g.yo((0,g.x)(function(){this.Ts(c)},this),0));
var d=gta();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},$7=function(a){return new R7(a.A.getPlayerContextData())},ita=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Oa(this.FK,b),this))},a)},jta=function(a){(0,g.y)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){jta(a);
a.A.setPlayerContextData(X7(b));ita(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.H),a.w.removeMediaListener(a.D),a.pk(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.H),a.w.addMediaListener(a.D),a.w.media.length&&a.pk(a.w.media[0]))},kta=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Jb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Jb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.Q.call(this);
this.B=NaN;this.R=!1;this.G=this.D=this.H=this.J=NaN;this.L=[];this.A=this.C=this.w=this.Qa=this.o=null;this.U=a;this.L.push(g.jr(window,"beforeunload",(0,g.x)(this.lD,this)));this.u=[];this.Qa=new R7;this.P=b.id;this.o=lta(this,c);this.o.subscribe("handlerOpened",this.JI,this);this.o.subscribe("handlerClosed",this.GI,this);this.o.subscribe("handlerError",this.HI,this);this.o.subscribe("handlerMessage",this.II,this);ysa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Qa.videoId;
g.QM()&&g.Kx("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},lta=function(a,b){return new c7(f7(a.U,"/bc"),b)},h8=function(a,b){a.S("proxyStateChange",b)},mta=function(a){a.B=g.yo((0,g.x)(function(){g8("Connecting timeout");
this.Uh(1)},a),2E4)},i8=function(a){g.Ao(a.B);
a.B=NaN},j8=function(a){g.Ao(a.J);
a.J=NaN},nta=function(a){k8(a);
a.H=g.yo((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.Ao(a.H);
a.H=NaN},pta=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.xv()&&a.Qa.reset(),h8(a,1),l8(a,"getNowPlaying"),ota(a)):a.Uh(1)},qta=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Qa.videoId&&(g.Yb(b.params)?a.Qa.o=null:a.Qa.o=b.params,a.S("remotePlayerChange"))},rta=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Qa.listId=b.params.listId||a.Qa.listId;W7(a.Qa,c,d);a.S("remoteQueueChange")},tta=function(a,b){b.params=b.params||{};
rta(a,b);sta(a,b);a.S("autoplayDismissed")},sta=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Qa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Qa.playerState&&(c=-1E3);a.Qa.playerState=c;c=Number(b.params.loadedTime);a.Qa.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Qa.G=isNaN(c)?0:c;c=a.Qa;var d=Number(b.params.liveIngestionTime);c.w=d;c.B=isNaN(d)?!1:!0;c=a.Qa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.A=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Qa.playerState?nta(a):k8(a);a.S("remotePlayerChange")},uta=function(a,b){if(-1E3!=
a.Qa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Qa.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Qa,isNaN(c)?0:c);a.S("remotePlayerChange")}},vta=function(a,b){var c="true"==b.params.muted;
a.Qa.volume=parseInt(b.params.volume,10);a.Qa.muted=c;a.S("remotePlayerChange")},wta=function(a,b){a.C=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},xta=function(a,b){var c="true"==b.params.hasNext;
a.Qa.Fe="true"==b.params.hasPrevious;a.Qa.hasNext=c;a.S("previousNextChange")},ota=function(a){g.Ao(a.G);
a.G=g.yo((0,g.x)(a.Uh,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.Qk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.Tc=a;this.u=[];this.u.push(this.Tc.$_s("screenChange",(0,g.x)(this.MN,this)));this.u.push(this.Tc.$_s("onlineScreenChange",(0,g.x)(this.jK,this)))},Cta=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.po("MDX_CONFIG")||b;nra();r6();n8||(n8=new e7(b?b.loungeApiHost:void 0),Cra()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ea("yt.mdx.remote.deferredProxies_",o8,void 0));yta();var c=p8();if(!c){var d=new v7(n8);g.Ea("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);cta(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ea("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.Qk(b)),s8.push(g.Fo("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),s8.push(g.Fo("yt-remote-cast2-receiver-selected",function(){t8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.Fo("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.Fo("yt-remote-cast2-session-change",zta)),s8.push(g.Fo("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),fta())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.up("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.Qk(a)),Ata(a),c.start(),q8()||Bta())},Eta=function(){var a=Dta();
N7()&&g.Lx("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Dta=function(){var a=p8().Tc.$_gos();
var b=w8();b&&x8()&&(m6(a,b)||a.push(b));return ura(a)},y8=function(){var a=Fta();
!a&&N7()&&eta()&&(a={key:"cast-selector-receiver",name:eta()});return a},Fta=function(){var a=Dta(),b=w8();
b||(b=u8());return g.Va(a,function(c){return b&&i6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().Kd();return n6(b,a)},zta=function(a){r8("remote.onCastSessionChange_: "+j6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},Gta=function(a){g.Ea("yt.mdx.remote.currentScreenId_",a,void 0)},Hta=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Ea("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||Gta("");g.Ea("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.y)(o8,function(c){c(a)}),o8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},u8=function(){var a=g.QM();
if(!a)return null;var b=p8().Kd();return n6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{Gta(a.id);var c=new f8(n8,a,v8());c.connect(b,Hta());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},Bta=function(){var a=u8();
a?(r8("Resume connection to: "+j6(a)),A8(a,0)):(s6(),fta(),r8("Skipping connecting because no session screen found."))},yta=function(){var a=v8();
if(g.Yb(a)){a=q6();var b=g.Lx("yt-remote-session-name")||"",c=g.Lx("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ea("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Ata=function(a){a?(g.Kx("yt-remote-session-app",a.app),g.Kx("yt-remote-session-name",a.name)):(f6("yt-remote-session-app"),f6("yt-remote-session-name"));
g.Ea("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.A.call(this);
this.B=a;this.u=b;this.w=new g.R(this);g.D(this,this.w);this.w.M(b,"onCaptionsTrackListChanged",this.EJ);this.w.M(b,"captionschanged",this.CI);this.w.M(b,"captionssettingschanged",this.bA);this.w.M(b,"videoplayerreset",this.zn);this.w.M(b,"mdxautoplaycancel",this.fC);this.P=this.w.M(b,"onVolumeChange",this.ty);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.Iy,this);c.subscribe("remotePlayerChange",this.rk,this);c.subscribe("remoteQueueChange",this.zn,this);c.subscribe("autoplayUpNext",this.iy,
this);c.subscribe("previousNextChange",this.Fy,this);c.subscribe("nowAutoplaying",this.By,this);c.subscribe("autoplayDismissed",this.hy,this);this.suggestion=null;this.H=new g.gF(64);this.A=new g.K(this.Yz,500,this);g.D(this,this.A);this.C=new g.K(this.Zz,1E3,this);g.D(this,this.C);this.R=new w6(this.pN,0,this);g.D(this,this.R);this.D={};this.L=new g.K(this.FA,1E3,this);g.D(this,this.L);this.J=new g.kl(this.RF,1E3,this);g.D(this,this.J);this.U=g.Fa;this.bA();this.zn();this.rk()},H8=function(a,b){var c=
a.B,d=a.u.getVideoData().lengthSeconds;
c.L=b||0;c.player.S("progresssync",b,d)},Ita=function(a){H8(a,0);
a.A.stop();I8(a,new g.gF(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.dc(c,b));a.o.Oz(a.u.getVideoData(1).videoId,c);a.D=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.He,gra(c));I8(a,new g.gF(1))},Jta=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{DR:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.mF(c,b)){var d=g.V(b,2);d!=g.V(a.H,2)&&g.XT(a.u.app,d);a.H=b;Kta(a.B,c,b)}},M8=function(){g.X.call(this,{F:"div",
I:"ytp-mdx-popup-dialog",N:{role:"dialog"},K:[{F:"div",I:"ytp-mdx-popup-dialog-inner-content",K:[{F:"div",I:"ytp-mdx-popup-title",W:"You're signed out"},{F:"div",I:"ytp-mdx-popup-description",W:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{F:"div",I:"ytp-mdx-privacy-popup-buttons",K:[{F:"button",X:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancel"},{F:"button",X:["ytp-button","ytp-mdx-privacy-popup-confirm"],
W:"Confirm"}]}]}]});this.w=new g.WM(this,250);g.D(this,this.w);this.D=this.u["ytp-mdx-privacy-popup-cancel"];this.M(this.D,"click",this.A);this.B=this.u["ytp-mdx-privacy-popup-confirm"];this.M(this.B,"click",this.C)},N8=function(a){g.X.call(this,{F:"div",
I:"ytp-remote",K:[{F:"div",I:"ytp-remote-display-status",K:[{F:"div",I:"ytp-remote-display-status-icon",K:[g.YM()]},{F:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.w=new g.WM(this,250);g.D(this,this.w);this.A=a;this.M(a,"presentingplayerstatechange",this.B);Lta(this,g.ZK(a))},Lta=function(a,b){if(3==a.A.getPresentingPlayerType()){var c={RECEIVER_NAME:a.A.getOption("remote","currentReceiver").name};
c=g.V(b,128)?g.DN("Error on $RECEIVER_NAME",c):g.nF(b)||g.V(b,4)?g.DN("Playing on $RECEIVER_NAME",c):g.DN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.w.show()}else a.w.hide()},O8=function(a,b){g.zP.call(this,"Play on",0,a,b);
this.w=a;this.D={};this.M(a,"onMdxReceiversChange",this.L);this.M(a,"presentingplayerstatechange",this.L);this.L()},P8=function(a){g.IQ.call(this,a);
this.u={key:l6(),name:"This computer"};this.B=null;this.A=[];this.P=this.o=null;this.J=[this.u];this.w=this.u;this.D=new g.gF(64);this.L=0;this.H=-1;this.C=null;if(!g.Qy(this.player.O())){a=this.player;var b=g.GK(a);b&&(b=b.ck())&&(b=new O8(a,b),g.D(this,b));b=new N8(a);g.D(this,b);g.rL(a,b.element,4);this.C=new M8;g.D(this,this.C);g.rL(a,this.C.element,4);this.R=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},Kta=function(a,b,c){a.D=
c;
a.player.S("presentingplayerstatechange",new g.sF(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.S(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.po("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.po("SESSION_INDEX")&&!g.po("LOGGED_IN")))||a.R||!a.C);if(c?0:a.player.O().og()||"WEB_EMBEDDED_PLAYER"==a.player.O().deviceParams.c)g.nF(g.ZK(a.player))?a.player.pauseVideo():(a.G=(0,g.x)(a.gM,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.w.show(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.va(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.He,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=gra(c))&&(d.locationInfo=c);c=d}else c=null;r8("Connecting to: "+g.Qk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):
!c&&C8()&&q8()==b.key?e6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().Kd(),(c=n6(c,b.key))&&A8(c,1))}},Sra={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},Mta={},qra={pO:"atp",MQ:"ska",BQ:"que",cQ:"mus",LQ:"sus",pP:"dsp",IQ:"seq"};
g6.prototype.Zf=function(){var a=new g6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.w=this.w;a.u=this.u;a.o=this.o};
var t6,p6="",Hra=Dra("loadCastFramework")||Dra("loadCastApplicationFramework"),bta=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Qa(w6,g.A);g.h=w6.prototype;g.h.hD=function(a){this.A=arguments;this.o=!1;this.Fa?this.w=(0,g.E)()+this.Uc:this.Fa=g.wf(this.B,this.Uc)};
g.h.stop=function(){this.Fa&&(g.v.clearTimeout(this.Fa),this.Fa=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.Y=function(){this.stop();w6.xb.Y.call(this)};
g.h.iD=function(){this.w?(this.Fa=g.wf(this.B,this.w-(0,g.E)()),this.w=null):(this.Fa=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},Lra(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Qa(Kra,z6);S8=new Kra;g.h=A6.prototype;g.h.ah=null;g.h.pe=!1;g.h.Xi=null;g.h.Qs=null;g.h.Ki=null;g.h.fi=null;g.h.Vf=null;g.h.Dg=null;g.h.wh=null;g.h.tc=null;g.h.Sk=0;g.h.we=null;g.h.jo=null;g.h.lg=null;g.h.Ej=-1;g.h.Jz=!0;g.h.Ng=!1;g.h.Ip=0;g.h.En=null;var Qra={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.tM=function(a){a=a.target;var b=this.En;b&&3==R6(a)?b.mm():this.NA(a)};
g.h.NA=function(a){try{if(a==this.tc)a:{var b=R6(this.tc),c=this.tc.C,d=this.tc.getStatus();if(g.Id&&!g.md(10)||g.Kd&&!g.ld("420+")){if(4>b)break a}else if(3>b||3==b&&!g.xh&&!T6(this.tc))break a;this.Ng||4!=b||7==c||(8==c||0>=d?this.o.oe(3):this.o.oe(2));K6(this);var e=this.tc.getStatus();this.Ej=e;var f=T6(this.tc);(this.pe=200==e)?(4==b&&G6(this),this.C?(Rra(this,b,f),g.xh&&this.pe&&3==b&&(this.A.ha(this.u,"tick",this.nM),this.u.start())):F6(this,f),this.pe&&!this.Ng&&(4==b?this.o.wn(this):(this.pe=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.lg=3,E6(13)):(this.lg=0,E6(14)),G6(this),H6(this))}}catch(k){this.tc&&T6(this.tc)}finally{}};
g.h.nM=function(){var a=R6(this.tc),b=T6(this.tc);this.Sk<b.length&&(K6(this),Rra(this,a,b),this.pe&&4!=a&&C6(this))};
g.h.JL=function(a){J6((0,g.x)(this.IL,this,a),0)};
g.h.IL=function(a){this.Ng||(K6(this),F6(this,a),C6(this))};
g.h.Qy=function(a){J6((0,g.x)(this.HL,this,a),0)};
g.h.HL=function(a){this.Ng||(G6(this),this.pe=a,this.o.wn(this),this.o.oe(4))};
g.h.cancel=function(){this.Ng=!0;G6(this)};
g.h.QL=function(){this.Xi=null;var a=(0,g.E)();0<=a-this.Qs?(2!=this.fi&&this.o.oe(3),G6(this),this.lg=2,E6(18),H6(this)):Ura(this,this.Qs-a)};
g.h.getLastError=function(){return this.lg};g.h=Xra.prototype;g.h.Gp=null;g.h.xd=null;g.h.Fn=!1;g.h.Gv=null;g.h.Ul=null;g.h.kq=null;g.h.Hp=null;g.h.be=null;g.h.yf=-1;g.h.Dj=null;g.h.gj=null;g.h.connect=function(a){this.Hp=a;a=M6(this.o,null,this.Hp);E6(3);this.Gv=(0,g.E)();var b=this.o.G;null!=b?(this.Dj=b[0],(this.gj=b[1])?(this.be=1,Yra(this)):(this.be=2,O6(this))):(b6(a,"MODE","init"),this.xd=new A6(this,void 0,void 0,void 0),this.xd.ah=this.Gp,B6(this.xd,a,!1,null,!0),this.be=0)};
g.h.gC=function(a){if(a)this.be=2,O6(this);else{E6(4);var b=this.o;b.Ee=b.Yf.yf;$6(b,9)}a&&this.oe(2)};
g.h.Zo=function(a){return this.o.Zo(a)};
g.h.abort=function(){this.xd&&(this.xd.cancel(),this.xd=null);this.yf=-1};
g.h.Fv=function(){return!1};
g.h.Jy=function(a,b){this.yf=a.Ej;if(0==this.be)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.Ee=this.yf;$6(c,2);return}this.Dj=c[0];this.gj=c[1]}else c=this.o,c.Ee=this.yf,$6(c,2);else if(2==this.be)if(this.Fn)E6(7),this.kq=(0,g.E)();else if("11111"==b){if(E6(6),this.Fn=!0,this.Ul=(0,g.E)(),c=this.Ul-this.Gv,!g.Id||g.md(10)||500>c)this.yf=200,this.xd.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.Ul=this.kq=(0,g.E)(),this.Fn=!1};
g.h.wn=function(){this.yf=this.xd.Ej;if(this.xd.pe)0==this.be?this.gj?(this.be=1,Yra(this)):(this.be=2,O6(this)):2==this.be&&((!g.Id||g.md(10)?!this.Fn:200>this.kq-this.Ul)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.be?E6(9):2==this.be&&E6(10);var a=this.o;this.xd.getLastError();a.Ee=this.yf;$6(a,2)}};
g.h.Hk=function(){return this.o.Hk()};
g.h.isActive=function(){return this.o.isActive()};
g.h.oe=function(a){this.o.oe(a)};g.Qa(P6,g.Je);var csa=/^https?$/i,Nta=["POST","PUT"];g.h=P6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.A="";this.C=0;this.Z=b;this.U=!1;this.w=!0;this.o=this.P?Mra(this.P):Mra(S8);this.L=this.P?this.P.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.Hv,this);try{d6(S6(this,"Opening Xhr")),this.da=!0,this.o.open(b,String(a),!0),this.da=!1}catch(f){d6(S6(this,"Error opening Xhr: "+f.message));bsa(this,f);return}a=c||
"";var e=this.headers.clone();d&&lra(d,function(f,k){e.set(k,f)});
d=g.Va(e.Yd(),$ra);c=g.v.FormData&&a instanceof g.v.FormData;!g.Ya(Nta,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.aa&&(this.o.responseType=this.aa);"withCredentials"in this.o&&this.o.withCredentials!==this.V&&(this.o.withCredentials=this.V);try{esa(this),0<this.D&&(this.R=Zra(this.o),d6(S6(this,"Will abort after "+this.D+"ms if incomplete, xhr2 "+this.R)),this.R?(this.o.timeout=this.D,this.o.ontimeout=(0,g.x)(this.Iv,this)):this.J=g.wf(this.Iv,this.D,this)),d6(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){d6(S6(this,"Send error: "+f.message)),bsa(this,f)}};
g.h.Iv=function(){"undefined"!=typeof g.d0&&this.o&&(this.A="Timed out after "+this.D+"ms, aborting",this.C=8,S6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(S6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.h.Y=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),Q6(this,!0));P6.xb.Y.call(this)};
g.h.Hv=function(){this.ia()||(this.da||this.G||this.B?dsa(this):this.HK())};
g.h.HK=function(){dsa(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=U6.prototype;g.h.rj=null;g.h.qd=null;g.h.Sb=null;g.h.Fp=null;g.h.Wl=null;g.h.eu=null;g.h.nm=null;g.h.kk=0;g.h.WH=0;g.h.Rc=null;g.h.fg=null;g.h.jf=null;g.h.Sg=null;g.h.Yf=null;g.h.fo=null;g.h.si=-1;g.h.lw=-1;g.h.Ee=-1;g.h.Vh=0;g.h.Qh=0;g.h.Og=8;var a7=new g.Je;g.Qa(gsa,g.je);g.Qa(hsa,g.je);g.Qa(isa,g.je);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.Fp=b;this.rj=c||{};d&&void 0!==e&&(this.rj.OSID=d,this.rj.OAID=e);this.C?(J6((0,g.x)(this.yu,this,a),100),msa(this)):this.yu(a)};
g.h.yu=function(a){this.Yf=new Xra(this);this.Yf.Gp=null;this.Yf.u=this.B;this.Yf.connect(a)};
g.h.Fv=function(){return 0==this.o};
g.h.Py=function(a){this.fg=null;psa(this,a)};
g.h.Oy=function(){this.jf=null;this.Sb=new A6(this,this.w,"rpc",this.D);this.Sb.ah=null;this.Sb.Ip=0;var a=this.eu.clone();$5(a,"RID","rpc");$5(a,"SID",this.w);$5(a,"CI",this.fo?"0":"1");$5(a,"AID",this.si);V6(this,a);if(!g.Id||g.md(10))$5(a,"TYPE","xmlhttp"),B6(this.Sb,a,!0,this.nm,!1);else{$5(a,"TYPE","html");var b=this.Sb,c=!!this.nm;b.fi=3;b.Vf=a6(a.clone());Tra(b,c)}};
g.h.Jy=function(a,b){if(0!=this.o&&(this.Sb==a||this.qd==a))if(this.Ee=a.Ej,this.qd==a&&3==this.o)if(7<this.Og){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Ia(c)&&3==c.length)if(0==c[0])a:{if(!this.jf){if(this.Sb)if(this.Sb.Ki+3E3<this.qd.Ki)X6(this),this.Sb.cancel(),this.Sb=null;else break a;Z6(this);E6(19)}}else this.lw=c[1],0<this.lw-this.si&&37500>c[2]&&this.fo&&0==this.Qh&&!this.Sg&&(this.Sg=J6((0,g.x)(this.yI,this),6E3));else $6(this,11)}else b!=Mta.NO.o&&$6(this,11);else if(this.Sb==a&&
X6(this),!g.ub(b)){c=this.B.parse(b);g.Ia(c);for(var d=0;d<c.length;d++){var e=c[d];this.si=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.nm=e[2],e=e[3],null!=e?this.Og=e:this.Og=6,this.o=3,this.Rc&&this.Rc.tu(),this.eu=M6(this,this.Hk()?this.nm:null,this.Fp),qsa(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.Rc&&this.Rc.ru(e),this.Qh=0)}}};
g.h.yI=function(){null!=this.Sg&&(this.Sg=null,this.Sb.cancel(),this.Sb=null,Z6(this),E6(20))};
g.h.wn=function(a){if(this.Sb==a){X6(this);this.Sb=null;var b=2}else if(this.qd==a)this.qd=null,b=1;else return;this.Ee=a.Ej;if(0!=this.o)if(a.pe)1==b?(b=(0,g.E)()-a.Ki,a7.dispatchEvent(new hsa(a7,a.wh?a.wh.length:0,b,this.Vh)),W6(this),this.A.length=0):qsa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ee)){if(d=1==b)this.qd||this.fg||1==this.o||2<=this.Vh?d=!1:(this.fg=J6((0,g.x)(this.Py,this,a),rsa(this,this.Vh)),this.Vh++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.BC=function(a){if(!g.Ya(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.eN=function(a){a?E6(2):(E6(1),ssa(this,8))};
g.h.Zo=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.V=!1;return a};
g.h.isActive=function(){return!!this.Rc&&this.Rc.isActive(this)};
g.h.oe=function(a){a7.dispatchEvent(new isa(a7,a))};
g.h.Hk=function(){return!(!g.Id||g.md(10))};
g.h=tsa.prototype;g.h.tu=function(){};
g.h.ru=function(){};
g.h.qu=function(){};
g.h.To=function(){};
g.h.Zu=function(){return{}};
g.h.isActive=function(){return!0};g.h=usa.prototype;g.h.isEmpty=function(){return g.Za(this.o)&&g.Za(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.Ya(this.o,a)||g.Ya(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.$na)(b,a);0<=c?(g.ab(b,c),b=!0):b=!1;return b||g.bb(this.u,a)};
g.h.md=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Qa(b7,g.A);g.h=b7.prototype;g.h.AL=function(){this.Uc=Math.min(3E5,2*this.Uc);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.Uc+15E3*Math.random();g.cn(this.o,a);this.u=(0,g.E)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Uc=5E3};g.Qa(c7,tsa);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.Hf=function(a){return this.w.bh(a)};
g.h.S=function(a,b){return this.w.S.apply(this.w,arguments)};
g.h.dispose=function(){this.fb||(this.fb=!0,g.he(this.w),xsa(this),g.he(this.u),this.u=null)};
g.h.ia=function(){return this.fb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.R),e=this.o;e&&(e.Rc=null);d.Rc=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.si):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.D.push(c):d7(this)&&nsa(this.o,c)};
g.h.tu=function(){this.u.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)nsa(this.o,a[b])}this.S("handlerOpened")};
g.h.qu=function(a){var b=2==a&&401==this.o.Ee;4==a||b||this.u.start();this.S("handlerError",a)};
g.h.To=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Zu=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.dc(a,this.B);return a};
g.h.ru=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),lsa(this.o)):this.S("handlerMessage",new vsa(a[0],a[1]))};
g.h.EM=function(){this.u.isActive();var a=this.o,b=0;a.Sb&&b++;a.qd&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var Fsa=(0,g.E)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Qa(m7,g.Q);m7.prototype.Kd=function(){return this.o};
m7.prototype.contains=function(a){return!!m6(this.o,a)};
m7.prototype.get=function(a){return a?n6(this.o,a):null};
m7.prototype.info=function(a){i7(this.D,a)};g.r(n7,g.Q);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Fa)&&this.RA()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Fa)||(g.Ao(this.Fa),this.Fa=NaN)};
g.h.Y=function(){this.stop();g.Q.prototype.Y.call(this)};
g.h.RA=function(){this.Fa=NaN;this.o=g.Cp(f7(this.C,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.x)(this.KN,this),onError:(0,g.x)(this.JN,this),Pd:(0,g.x)(this.LN,this)})};
g.h.KN=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.w;c.name=this.A;this.S("pairingComplete",new h6(c))};
g.h.JN=function(a){this.o=null;a.status&&404==a.status?this.u>=Ota.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=Ota[this.u],this.Fa=g.yo((0,g.x)(this.RA,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.h.LN=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var Ota=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Qa(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.S("screenChange");!g.Lx("yt-remote-lounge-token-expiration")&&Jsa(this);g.Ao(this.u);this.u=g.yo((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);Gsa(this,a);q7(this,!1);this.S("screenChange");b(a);a.token||Jsa(this)};
g.h.remove=function(a,b){var c=o7(this);Isa(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.h.bo=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.h.Y=function(){g.Ao(this.u);p7.xb.Y.call(this)};
g.h.sD=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.D,"Missed "+b+" lounge tokens.")};
g.h.rD=function(a){i7(this.D,"Requesting lounge tokens failed: "+a)};g.r(s7,g.Q);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.Lx("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.E)()-144E5<a?0:a)?u7(this):(this.A=(0,g.E)()+3E5,g.Kx("yt-remote-fast-check-period",this.A),this.Tr())};
g.h.isEmpty=function(){return g.Yb(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.Kb(this.o,function(c,d){return c&&!!n6(a,d)},this);
t7(this,b)};
g.h.Y=function(){g.Ao(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.Q.prototype.Y.call(this)};
g.h.Tr=function(){g.Ao(this.w);this.w=NaN;this.u&&this.u.abort();var a=Msa(this);if(c6(a)){var b=f7(this.B,"/pairing/get_screen_availability");this.u=g7(this.B,b,{lounge_token:g.Rb(a).join(",")},(0,g.x)(this.dL,this,a),(0,g.x)(this.cL,this))}else t7(this,{}),u7(this)};
g.h.dL=function(a,b){this.u=null;var c=g.Rb(Msa(this));if(g.pb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Jb("Changing Screen set during request."),this.Tr()};
g.h.cL=function(a){this.Jb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Jb=function(a){i7("OnlineScreenService",a)};g.Qa(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.S("screenChange"),this.u.isEmpty()||this.S("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.bo=function(a,b,c,d){this.w.contains(a)?this.w.bo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.D,a),d(Error(a)))};
g.h.Kd=function(a){return a?this.o:g.db(this.o,(0,g.Vd)(this.A,function(b){return!this.contains(b)},this))};
g.h.SA=function(){return(0,g.Vd)(this.Kd(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.TA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.he(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.he(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.NN=function(a,b,c,d){g.Cp(f7(this.C,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new h6(f.screen||{});if(!k.name||Qsa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Qsa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Pd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.Y=function(){g.he(this.w);g.he(this.u);v7.xb.Y.call(this)};
g.h.zD=function(){Rsa(this);this.S("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Qa(y7,g.Q);g.h=y7.prototype;g.h.yn=function(a){this.w=a;this.S("sessionScreen",this.w)};
g.h.Od=function(a){this.ia()||(a&&z7(this,""+a),this.w=null,this.S("sessionScreen",null))};
g.h.info=function(a){i7(this.L,a)};
g.h.VA=function(){return null};
g.h.gs=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.Y=function(){this.gs("");y7.xb.Y.call(this)};g.Qa(A7,y7);g.h=A7.prototype;g.h.ds=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Tsa(this)};
g.h.ti=function(a){this.info("launchWithParams no-op for Cast: "+g.Qk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.Od()},this),(0,g.x)(function(){this.Od(Error("Failed to stop receiver app."))},this)):this.Od(Error("Stopping cast device witout session."))};
g.h.gs=g.Fa;g.h.Y=function(){this.info("disposeInternal");g.Ao(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.xb.Y.call(this)};
g.h.bM=function(a,b){if(!this.ia())if(b){var c=x6(b);if(g.La(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Qk(c));switch(d){case "mdxSessionStatus":Ssa(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.zv=function(a,b,c,d){Psa(this.H,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.yo((0,g.x)(this.zv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.VA=function(){return this.o};
g.h.ON=function(a){this.ia()||a||(z7(this,"Cast session died."),this.Od())};g.Qa(B7,y7);g.h=B7.prototype;g.h.ds=function(a){this.A=a;this.A.addUpdateListener(this.R)};
g.h.ti=function(a){this.B=a;this.D()};
g.h.stop=function(){this.o();this.o=g.Fa;g.Ao(this.C);this.A?this.A.stop((0,g.x)(this.Od,this,null),(0,g.x)(this.Od,this,"Failed to stop DIAL device.")):this.Od()};
g.h.Y=function(){this.o();this.o=g.Fa;g.Ao(this.C);this.A&&this.A.removeUpdateListener(this.R);this.A=null;B7.xb.Y.call(this)};
g.h.RN=function(a){this.ia()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Fa,this.Od())};
g.h.Up=function(a){this.J=l6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,Vsa(this));a(b);Usa(this)}else this.D=(0,g.x)(function(){g.Ao(this.C);this.D=g.Fa;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Vsa(this));a(c);Usa(this)},this),this.C=g.yo((0,g.x)(function(){this.D()},this),100)};
g.h.UD=function(a,b,c){Psa(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.yn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Up(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.Up(b,c)},this))};g.Qa(C7,y7);C7.prototype.stop=function(){this.Od()};
C7.prototype.ds=g.Fa;C7.prototype.ti=function(){g.Ao(this.o);this.o=NaN;var a=n6(this.H.Kd(),this.u.label);a?this.yn(a):this.Od(Error("No such screen"))};
C7.prototype.Y=function(){g.Ao(this.o);this.o=NaN;C7.xb.Y.call(this)};g.Qa(D7,g.Q);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.D);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.MK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.Ly,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.ZI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ia()||
(chrome.cast.addReceiverActionListener(this.A),Csa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.UA,this)),this.w=Xsa(this),chrome.cast.setCustomReceivers(this.w,g.Fa,(0,g.x)(function(k){this.Jb("Failed to set initial custom receivers: "+g.Qk(k))},this)),this.S("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Jb("Failed to initialize API: "+g.Qk(k));
b(!1)},this))};
g.h.MM=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=n6(this.u.Kd(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=Wsa(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Fa,(0,g.x)(function(e){this.Jb("Failed to set initial custom receivers: "+g.Qk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.gs(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.OM=function(a){this.ia()?this.Jb("Setting connection data on disposed cast v2"):this.o?this.o.ti(a):this.Jb("Setting connection data without a session")};
g.h.QN=function(){this.ia()?this.Jb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.Ly,this),(0,g.x)(this.jL,this))};
g.h.Y=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.UA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=zsa,b=g.w("yt.mdx.remote.debug.handlers_");g.bb(b||[],a);g.he(this.o);D7.xb.Y.call(this)};
g.h.Jb=function(a){i7("Controller",a)};
g.h.My=function(a,b){this.o==a&&(b||G7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.h.IK=function(a,b){if(!this.ia())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.S("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Jb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Jb("Stopping receiver w/o session: "+a.friendlyName)}else this.Jb("onReceiverAction_ called without receiver.")};
g.h.ZI=function(a){if(this.ia())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Jb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Jb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Jb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.UD,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Up,b))};
g.h.Ly=function(a){if(!this.ia()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Jb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=n6(this.u.Kd(),c.label);d&&i6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.he(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.My,this,this.o)),this.o.ti(null));this.o.ds(a)}}};
g.h.PN=function(){return this.o?this.o.VA():null};
g.h.jL=function(a){this.ia()||(this.Jb("Failed to estabilish a session: "+g.Qk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.MK=function(a){E7("Receiver availability updated: "+a);if(!this.ia()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.S("yt-remote-cast2-availability-change",F7(this))}};
g.h.UA=function(){this.ia()||(this.w=Xsa(this),E7("Updating custom receivers: "+g.Qk(this.w)),chrome.cast.setCustomReceivers(this.w,g.Fa,(0,g.x)(function(){this.Jb("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.OM;D7.prototype.setConnectedScreenStatus=D7.prototype.MM;D7.prototype.stopSession=D7.prototype.QN;D7.prototype.getCastSession=D7.prototype.PN;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];R7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Fe=a.hasPrevious,this.hasNext=a.hasNext,this.D=a.playerTime,this.C=a.playerTimeAt,this.A=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.w=a.liveIngestionTime,this.B=
!isNaN(this.w))};
R7.prototype.isAdPlaying=function(){return 1081==this.playerState};
R7.prototype.getDuration=function(){return this.B?this.G+T7(this):this.G};
R7.prototype.clone=function(){return new R7(X7(this))};g.r(Z7,g.Q);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Fa,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.S("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Fa,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.S("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Fa,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.S("remotePlayerChange")}else a8(this,g.Oa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Fa,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.S("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Jb("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Jb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Oa(this.setVolume,a,b))};
g.h.Oz=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Qk(b.style),g.dc(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Oa(this.Oz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Oa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Qk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.QA=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Oa(this.QA,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Oa(this.nextVideo,a,b))};
g.h.Fu=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.Fu)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.Q.prototype.dispose.call(this)};
g.h.Y=function(){jta(this);this.A=null;this.B.clear();Y7(this,null);g.Q.prototype.Y.call(this)};
g.h.Ts=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.Za(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.FK=function(a,b){this.S(a,b)};
g.h.FI=function(a){if(!a)this.pk(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.pk=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),kta(this),this.S("remotePlayerChange")};
g.h.DI=function(a){a?(kta(this),this.S("remotePlayerChange")):this.pk(null)};
g.h.SI=function(){var a=gta();a&&Y7(this,a)};
g.h.Jb=function(a){i7("CP",a)};g.r(f8,g.Q);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Qa.listId=c);this.Qa.videoId=d;this.Qa.index=k||0;this.Qa.state=3;U7(this.Qa,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.Qk(l));this.o.connect({method:"setPlaylist",
params:g.Qk(l)},a,xra())}else g8("Connecting without params"),this.o.connect({},a,xra());mta(this)};
g.h.dispose=function(){this.ia()||(this.S("beforeDispose"),h8(this,3));g.Q.prototype.dispose.call(this)};
g.h.Y=function(){i8(this);k8(this);j8(this);g.Ao(this.D);this.D=NaN;g.Ao(this.G);this.G=NaN;this.w=null;g.kr(this.L);this.L.length=0;this.o.dispose();g.Q.prototype.Y.call(this);this.A=this.C=this.u=this.Qa=this.o=null};
g.h.lD=function(){this.Uh(2)};
g.h.JI=function(){g8("Channel opened");this.R&&(this.R=!1,j8(this),this.J=g.yo((0,g.x)(function(){g8("Timing out waiting for a screen.");this.Uh(1)},this),15E3));
Bra(wsa(this.o),this.P)};
g.h.GI=function(){g8("Channel closed");isNaN(this.B)?s6(!0):s6();this.dispose()};
g.h.HI=function(a){s6();isNaN(this.xj())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,g8("Channel error: "+a+" with reconnection in "+this.xj()+" ms"),h8(this,2))};
g.h.II=function(a){a.params?g8("Received: action="+a.action+", params="+g.Qk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.H)(a,function(c){return new g6(c)});
a=!!g.Va(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
pta(this,a);break;case "loungeScreenDisconnected":g.cb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
pta(this,!1);break;case "remoteConnected":var b=new g6(x6(a.params.device));g.Va(this.u,function(c){return b?c.id==b.id:!1})||hra(this.u,b);
break;case "remoteDisconnected":b=new g6(x6(a.params.device));g.cb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":rta(this,a);break;case "nowPlaying":tta(this,a);break;case "onStateChange":sta(this,a);break;case "onAdStateChange":uta(this,a);break;case "onVolumeChanged":vta(this,a);break;case "onSubtitlesTrackChanged":qta(this,a);break;case "nowAutoplaying":wta(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.S("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.S("autoplayModeChange",this.A);"DISABLED"==this.A&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":xta(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.BM=function(){if(this.w){var a=this.w;this.w=null;this.Qa.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.aD=function(){var a=3;this.ia()||(a=0,isNaN(this.xj())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.Uh=function(a){g8("Disconnecting with "+a);i8(this);this.S("beforeDisconnect",a);1==a&&s6();xsa(this.o,a);this.dispose()};
g.h.ZC=function(){var a=this.Qa;this.w&&(a=this.Qa.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.PM=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Qa.videoId&&(this.w=b.videoId,g.Ao(this.D),this.D=g.yo((0,g.x)(this.BM,this),5E3));var c=[];this.Qa.listId==b.listId&&this.Qa.videoId==b.videoId&&this.Qa.index==b.index||c.push("remoteQueueChange");this.Qa.playerState==b.playerState&&this.Qa.volume==b.volume&&this.Qa.muted==b.muted&&V7(this.Qa)==V7(b)&&g.Qk(this.Qa.o)==g.Qk(b.o)||c.push("remotePlayerChange");this.Qa.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.h.xv=function(){var a=this.o.C.id,b=g.Va(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.xj=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.E)():NaN};
g.h.OC=function(){return this.A||"UNSUPPORTED"};
g.h.PC=function(){return this.C||""};
g.h.IN=function(){if(!isNaN(this.xj())){var a=this.o.u;g.dn(a.o);a.start()}};
g.h.JM=function(a,b){l8(this,a,b);ota(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.Hf;f8.prototype.getProxyState=f8.prototype.aD;f8.prototype.disconnect=f8.prototype.Uh;f8.prototype.getPlayerContextData=f8.prototype.ZC;f8.prototype.setPlayerContextData=f8.prototype.PM;f8.prototype.getOtherConnectedRemoteId=f8.prototype.xv;f8.prototype.getReconnectTimeout=f8.prototype.xj;f8.prototype.getAutoplayMode=f8.prototype.OC;f8.prototype.getAutoplayVideoId=f8.prototype.PC;f8.prototype.reconnect=f8.prototype.IN;
f8.prototype.sendMessage=f8.prototype.JM;g.r(m8,m7);g.h=m8.prototype;g.h.Kd=function(a){return this.Tc.$_gs(a)};
g.h.contains=function(a){return!!this.Tc.$_c(a)};
g.h.get=function(a){return this.Tc.$_g(a)};
g.h.start=function(){this.Tc.$_st()};
g.h.add=function(a,b,c){this.Tc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Tc.$_r(a,b,c)};
g.h.bo=function(a,b,c,d){this.Tc.$_un(a,b,c,d)};
g.h.Y=function(){for(var a=0,b=this.u.length;a<b;++a)this.Tc.$_ubk(this.u[a]);this.u.length=0;this.Tc=null;m7.prototype.Y.call(this)};
g.h.MN=function(){this.S("screenChange")};
g.h.jK=function(){this.S("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.NN;v7.prototype.$_gsppc=v7.prototype.TA;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.bo;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.Kd;v7.prototype.$_gos=v7.prototype.SA;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.Hf;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.A);g.h=G8.prototype;
g.h.Y=function(){g.A.prototype.Y.call(this);this.A.stop();this.C.stop();this.R.stop();this.U();this.o.unsubscribe("proxyStateChange",this.Iy,this);this.o.unsubscribe("remotePlayerChange",this.rk,this);this.o.unsubscribe("remoteQueueChange",this.zn,this);this.o.unsubscribe("autoplayUpNext",this.iy,this);this.o.unsubscribe("previousNextChange",this.Fy,this);this.o.unsubscribe("nowAutoplaying",this.By,this);this.o.unsubscribe("autoplayDismissed",this.hy,this);this.o=this.B=null};
g.h.bx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==$7(this.o).playerState?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.mm(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.CI=function(a){this.R.hD(a)};
g.h.pN=function(a){this.bx("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.bA=function(){var a=this.u.getOption("captions","track");g.Yb(a)||K8(this,a)};
g.h.ty=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.rk,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.L.start();this.o.subscribe("remotePlayerChange",this.rk,this)}};
g.h.EJ=function(){g.Yb(this.D)||Jta(this,this.D);this.G=!1};
g.h.Iy=function(a,b){this.C.stop();2==b&&this.Zz()};
g.h.rk=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.gF(8));this.Yz();break;case 1085:case 3:I8(this,new g.gF(9));break;case 1083:case 0:I8(this,new g.gF(2));this.J.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.gF(4));break;case 2:I8(this,new g.gF(4));H8(this,V7(a));
break;case -1:I8(this,new g.gF(64));break;case -1E3:I8(this,new g.gF(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=$7(this.o).o;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,Jta(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.L.isActive()||this.FA()}else Ita(this)};
g.h.Fy=function(){this.u.S("mdxpreviousnextchange")};
g.h.zn=function(){J8(this)||Ita(this)};
g.h.fC=function(){this.o.Fu()};
g.h.iy=function(){};
g.h.By=function(a){isNaN(a)||this.u.S("mdxnowautoplaying",a)};
g.h.hy=function(){this.u.S("mdxautoplaycanceled")};
g.h.RF=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.FA=function(){if(J8(this)){var a=$7(this.o);this.w.Ua(this.P);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.P=this.w.M(this.u,"onVolumeChange",this.ty)}};
g.h.Yz=function(){this.A.stop();if(!this.o.ia()){var a=$7(this.o);1==a.playerState&&I8(this,new g.gF(8));H8(this,V7(a));this.A.start()}};
g.h.Zz=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.X);M8.prototype.A=function(){e6("mdx-privacy-popup-cancel");this.w.hide()};
M8.prototype.C=function(){e6("mdx-privacy-popup-confirm");this.w.hide()};g.r(N8,g.X);N8.prototype.B=function(a){Lta(this,a.state)};g.r(O8,g.zP);O8.prototype.L=function(){var a=this.w.getOption("remote","receivers");a&&1<a.length&&!this.w.getOption("remote","quickCast")?(this.D=g.rb(a,this.C,this),g.BP(this,(0,g.H)(a,this.C)),a=this.w.getOption("remote","currentReceiver"),this.fe(this.C(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.C=function(a){return a.key};
O8.prototype.me=function(a){return"cast-selector-receiver"==a?"Cast...":this.D[a].name};
O8.prototype.Mc=function(a){g.zP.prototype.Mc.call(this,a);this.w.setOption("remote","currentReceiver",this.D[a]);this.A.bb()};g.r(P8,g.IQ);g.h=P8.prototype;
g.h.create=function(){Cta(g.Hy(this.player.O()));this.A.push(g.Fo("yt-remote-before-disconnect",this.zI,this));this.A.push(g.Fo("yt-remote-connection-change",this.NK,this));this.A.push(g.Fo("yt-remote-receiver-availability-change",this.Gy,this));this.A.push(g.Fo("yt-remote-auto-connect",this.LK,this));this.A.push(g.Fo("yt-remote-receiver-resumed",this.KK,this));this.A.push(g.Fo("mdx-privacy-popup-confirm",this.qM,this));this.A.push(g.Fo("mdx-privacy-popup-cancel",this.pM,this));this.Gy()};
g.h.load=function(){this.player.cancelPlayback();g.IQ.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=Hta())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.L=a||0,this.player.S("progresssync",a,void 0));Kta(this,this.D,this.D);g.dU(this.player.app,6)};
g.h.unload=function(){this.player.S("mdxautoplaycanceled");this.w=this.u;g.ie(this.B,this.o);this.o=this.B=null;g.IQ.prototype.unload.call(this);g.dU(this.player.app,5);Q8(this)};
g.h.Y=function(){g.Lo(this.A);g.IQ.prototype.Y.call(this)};
g.h.ak=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.bx.apply(this.B,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.H};
g.h.cD=function(){return this.loaded?this.B.suggestion:null};
g.h.Fe=function(){return this.o?$7(this.o).Fe:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.L};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.S(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.lc():!a.isAdPlaying()&&this.player.lc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.B?a.w+T7(a):a.w,isAtLiveHead:1>=(a.B?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.B?a.u+T7(a):a.u,seekableStart:0<a.A?a.A+T7(a):
a.A}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.FF=function(){this.o&&this.o.QA()};
g.h.zI=function(a){1==a&&(this.P=this.o?$7(this.o):null)};
g.h.NK=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.P=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.he(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.P)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Gy=function(){this.J=[this.u].concat(Eta());var a=y8()||this.u;R8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.gM=function(a){!this.R&&g.uF(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.LK=function(){var a=y8();R8(this,a)};
g.h.KK=function(){this.w=y8()};
g.h.qM=function(){this.R=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.pM=function(){this.R=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.wc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.J;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.J.length&&"cast-selector-receiver"==this.J[1].key?(b&&P7(),!0):!1}};
g.h.GF=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Xe=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.YQ.remote=P8;})(_yt_player);
